# -*- coding: utf-8 -*-
"""Untitled15.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iWhQd4h64JaAAHDW1uzw-LeGR9jVGNzF
"""

# ==========================================
# SISTEMA DE GESTIÓN DE NOTAS
# ==========================================

# Lista para guardar estudiantes
estudiantes = []

# Función para agregar estudiante
def agregar_estudiante():
    nombre = input("Ingrese el nombre del estudiante: ")

    try:
        nota = float(input("Ingrese la nota del estudiante: "))

        if nota < 0 or nota > 10:
            print("La nota debe estar entre 0 y 10")
            return

        estudiantes.append([nombre, nota])
        print("Estudiante agregado correctamente")

    except:
        print("Error: Ingrese una nota válida")


# Función para mostrar estudiantes
def mostrar_estudiantes():

    if len(estudiantes) == 0:
        print("No existen estudiantes registrados")
        return

    print("\n===== LISTA DE ESTUDIANTES =====")

    for i, estudiante in enumerate(estudiantes, start=1):
        print(f"{i}. {estudiante[0]} - Nota: {estudiante[1]}")


# Función para calcular promedio
def calcular_promedio():

    if len(estudiantes) == 0:
        print("No hay datos para calcular")
        return

    suma = 0

    for estudiante in estudiantes:
        suma += estudiante[1]

    promedio = suma / len(estudiantes)

    print(f"\nPromedio general: {promedio:.2f}")


# Función para mostrar aprobados y reprobados
def mostrar_estado():

    if len(estudiantes) == 0:
        print("No hay estudiantes registrados")
        return

    print("\n===== RESULTADOS =====")

    for estudiante in estudiantes:

        if estudiante[1] >= 7:
            estado = "APROBADO"
        else:
            estado = "REPROBADO"

        print(f"{estudiante[0]} - {estado}")


# Función para buscar estudiante
def buscar_estudiante():

    if len(estudiantes) == 0:
        print("No existen registros")
        return

    nombre_buscar = input("Ingrese el nombre a buscar: ")

    encontrado = False

    for estudiante in estudiantes:

        if estudiante[0].lower() == nombre_buscar.lower():
            print(f"Estudiante encontrado:")
            print(f"Nombre: {estudiante[0]}")
            print(f"Nota: {estudiante[1]}")
            encontrado = True

    if not encontrado:
        print("Estudiante no encontrado")


# Función para ordenar estudiantes
def ordenar_notas():

    if len(estudiantes) == 0:
        print("No hay datos")
        return

    estudiantes.sort(key=lambda x: x[1], reverse=True)

    print("\nEstudiantes ordenados de mayor a menor nota")


# Menú principal
while True:

    print("\n========== MENÚ ==========")
    print("1. Agregar estudiante")
    print("2. Mostrar estudiantes")
    print("3. Calcular promedio")
    print("4. Mostrar aprobados/reprobados")
    print("5. Buscar estudiante")
    print("6. Ordenar notas")
    print("7. Salir")

    opcion = input("Seleccione una opción: ")

    if opcion == "1":
        agregar_estudiante()

    elif opcion == "2":
        mostrar_estudiantes()

    elif opcion == "3":
        calcular_promedio()

    elif opcion == "4":
        mostrar_estado()

    elif opcion == "5":
        buscar_estudiante()

    elif opcion == "6":
        ordenar_notas()

    elif opcion == "7":
        print("Programa finalizado")
        break

    else:
        print("Opción inválida")